# Generated by Django 4.2.30 on 2026-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("joining_date", models.DateField(auto_now_add=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                (
                    "id_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="students/id_proofs/"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="students_full_na_365b2b_idx"
                    ),
                    models.Index(fields=["phone"], name="students_phone_8a36df_idx"),
                    models.Index(
                        fields=["student_code"], name="students_student_cdda5e_idx"
                    ),
                ],
            },
        ),
    ]
