# Generated by Django 4.2.30 on 2026-08-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("shifts", "0001_initial"),
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("vacated", "Vacated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("vacated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vacate_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_membership",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewed_into",
                        to="memberships.membership",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="seats.seat",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "memberships",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MembershipShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_shifts",
                        to="memberships.membership",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_shifts",
                        to="seats.seat",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_shifts",
                        to="shifts.shift",
                    ),
                ),
            ],
            options={
                "db_table": "membership_shifts",
                "indexes": [
                    models.Index(
                        fields=["seat", "shift", "is_active"],
                        name="membership__seat_id_8cc48d_idx",
                    ),
                    models.Index(
                        fields=["membership"], name="membership__members_9ebee8_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membershipshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("seat", "shift"),
                name="unique_active_seat_shift",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["status"], name="memberships_status_3164d9_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["expiry_date"], name="memberships_expiry__739033_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["student", "status"], name="memberships_student_cfd319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["seat", "status"], name="memberships_seat_id_253c58_idx"
            ),
        ),
    ]
