# Generated by Django 4.2.30 on 2026-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("disabled", "Disabled")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seats",
                "ordering": ["number"],
                "indexes": [
                    models.Index(fields=["number"], name="seats_number_7ab68b_idx"),
                    models.Index(fields=["status"], name="seats_status_1a0561_idx"),
                ],
            },
        ),
    ]
