# Generated by Django 4.2.30 on 2026-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibrarySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_name", models.CharField(default="LibraryOS", max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("total_seats", models.PositiveIntegerField(default=50)),
                (
                    "default_monthly_fee",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                (
                    "membership_duration_policy",
                    models.CharField(
                        choices=[
                            ("calendar_month", "Same date next month"),
                            ("30_days", "Fixed 30 days"),
                        ],
                        default="calendar_month",
                        max_length=20,
                    ),
                ),
                ("expiring_soon_days", models.PositiveIntegerField(default=3)),
                (
                    "default_payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("currency_symbol", models.CharField(default="₹", max_length=4)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "library_settings",
            },
        ),
    ]
