# Generated by Django 4.2.30 on 2026-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarysettings",
            name="apply_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="notify_daily_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="notify_due_payment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="notify_expiry",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="notify_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="receipt_footer_text",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="tax_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="tax_label",
            field=models.CharField(default="GST", max_length=20),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="website",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
